apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.backend_tasks_app.secretName}}
  namespace: {{.Values.backend_tasks_app.namespace}}
type: Opaque
stringData:
  DB_NAME: tasksdb
  DB_USER: postgres
  DB_PASSWORD: seguro12345
  DB_HOST: tasks-db-svc
  DB_PORT: '5432'
  CORS_ALLOWED_ORIGINS: "http://tasks-app.local,http://192.168.9.11,http://localhost:5173"
  ALLOWED_HOSTS: "tasks-app.local,api-tasks.local,192.168.9.11,localhost,127.0.0.1"
  DEBUG: FALSE
  SECRET_KEY: 'django-insecure-dvgfdz173tpwbga%!)h0vthnt3=3mv*d^dhk3^u#5%k-t%h!dd' 