apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.frontend_tasks_app.secretName}}
  namespace: {{.Values.frontend_tasks_app.namespace}}
type: Opaque
stringData:

  VITE_API_URL_PLACEHOLDER: "http://api-tasks.local/api/v1/tasks/"