apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.frontend_tasks_app.secretName}}
  namespace: {{.Values.frontend_tasks_app.namespace}}
type: Opaque
stringData:

    VITE_BASE_URL: "http://tasks-app.local/api/v1/task/"