apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.Values.tasks_db.name}}
  namespace: {{.Values.tasks_db.namespace}}
spec:
  selector:
    matchLabels:
      app: {{.Values.tasks_db.name}}
  serviceName: {{.Values.tasks_db.serviceName}}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{.Values.tasks_db.name}}
    spec:
      securityContext:
        fsGroup: 70
      serviceAccountName: {{.Values.tasks_db.serviceAccountName}}
      containers:
        - name: {{.Values.tasks_db.name}}
          image: "{{.Values.tasks_db.repository}}:{{.Values.tasks_db.tag}}"
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{.Values.tasks_db.secretName}}
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{.Values.tasks_db.secretName}}
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{.Values.tasks_db.secretName}}
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: {{.Values.tasks_db.volumeName}}
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: {{.Values.tasks_db.volumeName}}
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.tasks_db.serviceName}}
  namespace: {{.Values.tasks_db.name}}
spec:
  clusterIP: None
  selector:
    app: {{.Values.tasks_db.name}}
  ports:
    - port: 5432
      targetPort: 5432
