apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.frontend-tasks-app.secretName}}
  namespace: {{.Values.frontend-tasks-app.namespace}}
type: Opaque
stringData:

    VITE_BASE_URL: "http://backend-tasks-svc/api/v1/task/"